#!/bin/bash
#
#ldcmd ref  https://openwrt.org/docs/guide-developer/source-code/start
#

function ld_updatecmd()
{
wget -O /etc/dockerscript https://raw.githubusercontent.com/gzmud/prvscript/master/dockerscript
. /etc/dockerscript
echo "ld_updatecmd complete"
}

function _ld_updatecmd()
{
wget -O dockerscript https://raw.githubusercontent.com/gzmud/prvscript/master/dockerscript
. dockerscript
echo "ld_updatecmd complete"
}

function _ld_set()
{
ldpkg='luci luci-ssl luci-theme-material luci-i18n-base-zh-cn kmod-usb-net kmod-usb-net-rtl8152 kmod-usb-ohci kmod-usb-storage kmod-usb-hid kmod-usb2 kmod-fs-vfat kmod-fs-ext4 curl nano ip-full ipset iptables-mod-tproxy libev libpthread libpcre libssh2 libcares libstdcpp libmbedtls coreutils coreutils-base64 ca-certificates ca-bundle bind-dig mtd mount-utils block-mount ntfs-3g-utils minidlna samba36-server miniupnpd shadow-utils
shadow-useradd usbutils luci-app-minidlna luci-i18n-minidlna-zh-cn luci-app-samba luci-i18n-samba-zh-cn luci-app-upnp luci-i18n-upnp-zh-cn aria2 webui-aria2 yaaw luci-app-aria2 luci-i18n-aria2-zh-cn libudns libsodium shadowsocks-libev shadowsocks-libev-server luci-app-shadowsocks ChinaDNS luci-app-chinadns dns-forwarder luci-app-dns-forwarder wget'
ldmyipk='aria2 webui-aria2 yaaw'
#lddir=$(readlink -f .)
ldmkopt='-j4'
ldbrach='master'
}

function _ld_gitit()
{
	tmpresult=0
	test -d $2 && ( pushd $2; git pull ; popd ; return 1 ) || git clone $1 $2
	return $tmpresult
}

function _ld_getmy()
{
./scripts/feeds uninstall shadowsocks-libev
_ld_gitit https://github.com/shadowsocks/openwrt-shadowsocks.git package/shadowsocks-libev
_ld_gitit https://github.com/aa65535/openwrt-chinadns.git package/chinadns
_ld_gitit https://github.com/aa65535/openwrt-dns-forwarder.git package/dns-forwarder
_ld_gitit https://github.com/aa65535/openwrt-simple-obfs.git package/simple-obfs
_ld_gitit https://github.com/shadowsocks/luci-app-shadowsocks.git package/luci-app-shadowsocks
_ld_gitit https://github.com/aa65535/openwrt-dist-luci.git package/openwrt-dist-luci
}

function ld_build()
{
	make -j4 tools/compile
	make -j1 tools/cmake/compile
	make -j4 tools/compile
	make -j4 toolchain/compile
	make -j1 toolchain/compile
	make -j4
	#make target/linux/compile -j4 V=99
	#make target/compile -j4
	#make package/compile -j4
}

function ld_make()
{
#ld_getsrc
#ld_update
ld_modcfg
ld_kerconf || return $?
ld_build
}

function ld_kerconf()
{
make kernel_menuconfig CONFIG_TARGET=subtarget -j4
return $?
}

function _ld_checkcfg()
{
awk -v ldpkg="$ldpkg" 'BEGIN {gsub(/ +/," ",ldpkg);tLen = split(ldpkg,tNeed," ")};{for(k in tNeed ){if ($0 ~ "_"tNeed[k]"=y") {print $0;tHave[k]=tNeed[k];delete tNeed[k] } else if ($0 ~ "_"tNeed[k]" " ){ print "\033[40;33m"$0"\033[0m"} }}; END {for(k in tNeed ){ print tNeed[k] };print length(tNeed)}' .config
}

function _ld_setpkg()
{
awk '/^[ \t]*#.*CONFIG_PACKAGE_'$1'[ \t]/{print CONFIG_PACKAGE_'$1'=y}' .config
}

function _ld_getpkg()
{
awk '/^[ \t]*CONFIG_PACKAGE_'$1'[ \t=]*/{gsub("/^[ \t]*CONFIG_PACKAGE_'$1'[ \t=]*/","",$0);print CONFIG_PACKAGE_'$1'=y}' .config
}

function ld_modcfg()
{
make defconfig
ld_checkconfig >>.config
make defconfig
sed -i 's/CONFIG_BRCM2708_SD_BOOT_PARTSIZE\=20/CONFIG_BRCM2708_SD_BOOT_PARTSIZE\=100/' .config
sed -i 's/CONFIG_TARGET_ROOTFS_PARTSIZE\=256/CONFIG_TARGET_ROOTFS_PARTSIZE\=768/' .config
ld_checkconfig >>.config
make defconfig
}

function ld_checkconfig()
{
    for i in $ldpkg
    do
    awk '{if(match ($0,/^([ #\t]*)(CONFIG_PACKAGE_'$i')[ \t=]+(.*)$/,m)){pkg["'$i'"]=1;print m[2]"=y"}} END {if (!pkg["'$i'"]) {print "#'$i'"}}' .config
    done
}

function ld_testredun()
{
 awk '{if(match ($0,/^[# \t]*(CONFIG_PACKAGE_[^= \t]*)[ \t=]+(.*)$/,m)){p[m[1]]++}}END{for (a in p) {if (--p[a]) print a,p[a]++}}' .config
}

function ld_pkgprobe()
{
#ld_pkgcheck $1 && return 1
 awk '{if(match ($0,/^[# \t]*(CONFIG_PACKAGE_[^= \t]*'$1'[^= \t]*)[ \t=]+(.*)$/,m)){p[m[1]]++}}END{for (a in p) { print a} ; exit length(p)}' .config
 return $?
}

function ld_pkgcheck()
{
awk '{if(match ($0,/^[# \t]*(CONFIG_PACKAGE_'$1')[ \t=]+(.*)$/,m)){p[m[1]]++}} END{for (a in p) {print a};exit !length(p)}' .config
return $?
}

function ld_savecfg()
{
    conffile=ldconf/$(date +%Y-%m-%d-%s).conf
	./scripts/diffconfig.sh > ~/prvscript/$conffile
    pushd ~/prvscript
    git pull
    git add conffile
    git commit -a -m "add $conffile"
    git push
    popd
}

function _ld_runonce()
{
test -d s && return 0
cd
_ld_gitit https://github.com/openwrt/openwrt.git s
cd s
git checkout $ldbrach
ld_setbcm2710
./scripts/feeds update -a
./scripts/feeds install -a
ln -s ~/lede/ ~/s/bin
_ld_getmy
}

function ld_run()
{
. /usr/share/bash-completion/bash_completion
cd
_ld_gitit https://github.com/openwrt/openwrt.git s && ln -s ~/lede/ ~/s/bin
cd s
#make distclean
git checkout $ldbrach
git pull
ld_setbcm2710
./scripts/feeds update -a
./scripts/feeds install -a
_ld_getmy
}

function ld_setbcm2710()
{
echo 'CONFIG_TARGET_brcm2708=y
CONFIG_TARGET_brcm2708_bcm2710=y
CONFIG_TARGET_brcm2708_bcm2710_DEVICE_rpi-3=y' > .config
}

function ld_main()
{
case $1 in
	ld_main|ld_run)
	{
		_ld_set
		ld_run
	}
	;;
	ld_updatecmd)
	{
		ld_updatecmd
	}
	;;
	*)
	echo "Unknow CMD" $@
	;;
esac
}

function ld_hello()
{
test -d s && return 0
echo hello
}

function ld_testawk()
{
echo '#
# Automatically generated file; DO NOT EDIT.
# LEDE Configuration
#
CONFIG_MODULES=y
CONFIG_HAVE_DOT_CONFIG=y
# CONFIG_TARGET_arm64 = = is not set
# CONFIG_TARGET_sunxi is not set
# CONFIG_TARGET_apm821xx is not set
#    CONFIG_TARGET_ath25 is not set
CONFIG_TARGET_ARCH_PACKAGES="arm_cortex-a53_neon-vfpv4"
CONFIG_DEFAULT_TARGET_OPTIMIZATION="-Os -pipe -mcpu=cortex-a53 -mfpu=neon-vfpv4"'
}

_ld_set
ld_main $@
#ld_setbcm2710
